// <auto-generated />
using System;
using CarePointApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarePointApp.Data.Migrations
{
    [DbContext(typeof(CarePointDataContext))]
    [Migration("20260928080418_AddSpecialityIdToDoctor")]
    partial class AddSpecialityIdToDoctor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarePointApp.Models.ClinicalStatus", b =>
                {
                    b.Property<int>("clinicalStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clinicalStatusId"));

                    b.Property<string>("clinicalStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clinicalStatusId");

                    b.ToTable("clinicalStatuses");
                });

            modelBuilder.Entity("CarePointApp.Models.Doctor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("doctorSpecialityId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("doctorSpecialityId");

                    b.ToTable("doctors");
                });

            modelBuilder.Entity("CarePointApp.Models.DoctorSpeciality", b =>
                {
                    b.Property<int>("doctorSpecialityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("doctorSpecialityId"));

                    b.Property<string>("doctorSpecialityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("doctorSpecialityId");

                    b.ToTable("doctorSpecialities");
                });

            modelBuilder.Entity("CarePointApp.Models.Patient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("bookInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("bookOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("clinicalStatusId")
                        .HasColumnType("int");

                    b.Property<int>("doctorId")
                        .HasColumnType("int");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nric")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("clinicalStatusId");

                    b.HasIndex("doctorId");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("CarePointApp.Models.Doctor", b =>
                {
                    b.HasOne("CarePointApp.Models.DoctorSpeciality", "speciality")
                        .WithMany()
                        .HasForeignKey("doctorSpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("speciality");
                });

            modelBuilder.Entity("CarePointApp.Models.Patient", b =>
                {
                    b.HasOne("CarePointApp.Models.ClinicalStatus", "clinicalStatus")
                        .WithMany()
                        .HasForeignKey("clinicalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarePointApp.Models.Doctor", "assignedDoctor")
                        .WithMany()
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assignedDoctor");

                    b.Navigation("clinicalStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
